### ISSUE TITLE
Docker Sample

### ISSUE THREAD

**Issue by robert-wallis** [WhiteHalmos/emailer#15]
Maybe it would be neat to have a `samples/` folder with a docker config, so it's easy to set up.  Here's what I'm using for now.  Not officially live yet on my side, but I got it to send a formatted dryrun meeting this week:

# Dockerfile
```
FROM python:alpine

MAINTAINER Robert Wallis <smilingrob@gmail.com>

RUN apk update && apk add ca-certificates git

RUN pip install 'emailer>=1.0'
RUN mkdir -p /var/emailer

WORKDIR /var/emailer
CMD ["email", "-v", "--active", "--dryrun", "-k", "mykey"]
```

# docker-compose.yml
```
version: "3"
services:
  emailer:
    build: .
    volumes:
      - .:/var/emailer
```
# crontab -e
```
55 18 * * * docker-compose run --rm emailer
```
